name: Docker Build

on:
  push:
    branches: 
      - "main"
    paths:
      - "**Dockerfile"
  pull_request_target:
    branches: 
      - "main"
    types:
      - opened
    #   - synchronize
    #   - reopened
    paths:
      - "**Dockerfile"
  workflow_dispatch:
    inputs:
      godot_version:
        description: 'Godot version to build'
        required: true
        default: '4.2.1'
      steamworks_version:
        description: 'Steamworks SDK version to use'
        required: true
        default: '1.59'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Get tag name
      id: get_ref
      run: echo "tag=${GITHUB_REF_NAME//\//_}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/steamrt-godot:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/steamrt-godot:${{ steps.get_ref.outputs.tag }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max,ignore-error=true
        build-args: |
          STEAMWORKS_COOKIE=${{ secrets.STEAMWORKS_COOKIE }}
          GODOT_VERSION=${{ github.event.inputs.godot_version }}
          STEAMWORKS_VERSION=${{ github.event.inputs.steamworks_version }}
