name: Docker Build

on:
  push:
    branches: 
      - "main"
    paths:
      - "**Dockerfile"
  pull_request_target:
    branches: 
      - "main"
    types:
      - opened
    #   - synchronize
    #   - reopened
    # paths:
    #   - "**Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/steamrt-godot:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/steamrt-godot:${{ github.ref_name//\//- }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          "STEAMWORKS_COOKIE=${{ secrets.STEAMWORKS_COOKIE }}"
