name: Release

on: 
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    container:
      image: robchio/steamrt-godot:latest
    steps:
    - name: Set archive filename
      run: |
        . /etc/os-release
        FILE_NAME=godot-${GODOT_VERSION}-${ID}-${VERSION_ID}-${VERSION_CODENAME}.tar.gz
        echo "file_name={FILE_NAME}" >> "$GITHUB_ENV"
        
    - name: Compress files
      run: tar -czvf ${{ env.file_name }} /.local/share/godot/templates/${GODOT_VERSION}.stable/
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ${{ env.file_name }}
        
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
      id: tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.output.new_tag }}
        fail_on_unmatched_files: true
        files: |
          ${{ env.file_name }}
